name: Compliance Feature

on:
  push:
    branches:
      - main
      - '**/feature/**'  # Optional: Include other branches if necessary
  pull_request:
    branches:
      - main
      - '**/feature/**'  # Include other branches as needed
      
jobs:
  example-job:
    name: Example Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    environment: development  # Example environment variable

    permissions:  # Token permissions for the job
      contents: read
      issues: write

    concurrency:  # Concurrency control
      group: example-group
      cancel-in-progress: true
