name: Example Pipeline

on:
  push:
    branches:
      - main
      - '**/feature/**'
  pull_request:
    branches:
      - main
      - '**/feature/**'

jobs:
  build-and-sbom:
    name: Build and Generate SBOM
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        run: |
          # Replace with your build command
          echo "Building the project..."
          mkdir -p ./build  # Ensure build directory exists

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./build/

      - name: Set build metadata
        run: echo "::set-output name=metadata_build::true"
        id: set_metadata

    environment: development

    permissions:
      contents: read
      issues: write

    concurrency:
      group: example-group
      cancel-in-progress: true
